### PR TITLE
Remove DESIGN.md

### PR DESCRIPTION
**Pull request by alishir**
#### Reference issue
Fixes #...

### CODE REVIEW

**Review by Sean-Der — APPROVED** [review]

**Comment by Sean-Der** [comment]
Thank you @alishir :)

**Comment by Sean-Der** [comment]
Hi @alishir 

wouls you mind updating your commit message to have a body.

**Comment by Sean-Der** [comment]
@alishir grabbed it myself, thanks for fixing that!

**Comment by alishir** [comment]
Sorry, I just read your message and it seems it is too late.

**Pull request merged**
